baseURL: "/"
title: "pulsifer.ca"
languageCode: "en-us"
theme: "wip"

params:
  portrait:
    path: "avatar-icons.svg"
    width: 75%
    altText: "Avatar with floating icons"
  social:
    instagram: jonpulsifer.ca
    github: jonpulsifer
    linkedin: jonpulsifer
    steam: jawn
    twitter: jonpulsifer

menus:
  main:
    - identifier: about
      name: about
      url: /about
    - identifier: archive
      name: archive
      url: /archive

markup:
  highlight:
    style: dracula

enableEmoji: true
